// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfvwhbjtjxigdqtefbtd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmdndoYmp0anhpZ2RxdGVmYnRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MDI5MDcsImV4cCI6MjA2NzI3ODkwN30.7kl8A_LYkU6O9leCrkmyDAi99Wv4ZxtEW6esGeG2-uw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});